services:
  backend:
    container_name: nestapp
    volumes:
      - type: bind
        source: .
        target: /app
    build: ./backend
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: file:./dev.db
    restart: always
    networks:
      - nestapp
  
  frontend:
    container_name: nextapp
    volumes:
      - type: bind
        source: .
        target: /app
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    restart: always
    depends_on:
      - backend
    networks:
      - nestapp

networks:
  nestapp:
    driver: bridge